#!/bin/sh

xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --mode 1920x1080i --pos 1920x0 --rotate normal

bspc desktop 1 -m eDP1
bspc desktop 2 -m HDMI2
bspc desktop 3 -m HDMI2
bspc desktop 4 -m HDMI2
bspc desktop 5 -m HDMI2
bspc desktop 6 -m HDMI2
bspc desktop 7 -m HDMI2
bspc desktop 8 -m HDMI2
bspc desktop 9 -m HDMI2
bspc desktop 0 -m HDMI2

  

bspc monitor HDMI2 -o 2 3 4 5 6 7 8 9 0
/home/red/.config/polybar/launch.sh &
