#!/bin/sh



bspc desktop 2 -m eDP1
bspc desktop 3 -m eDP1
bspc desktop 4 -m eDP1
bspc desktop 5 -m eDP1
bspc desktop 6 -m eDP1
bspc desktop 7 -m eDP1
bspc desktop 8 -m eDP1
bspc desktop 9 -m eDP1
bspc desktop 0 -m eDP1

  
xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal  --output HDMI2 --off

bspc monitor eDP1 -o 1 2 3 4 5 6 7 8 9 0
/home/red/.config/polybar/launch.sh &
