#! /bin/sh


#xrdb -load /home/red/.config/X11/Xresources
killall sxhkd
sxhkd &

#nitrogen --restore


bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 
bspc monitor HDMI2 -d  9

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focused_border_color   "#ffffff"
bspc config normal_border_color  "#000000"
bspc config border_width 2 
bspc config window_gap  10
bspc config top_padding 23
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a "Tor Browser" desktop='^5'
bspc rule -a Brave desktop='^2'
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Sxiv state=floating follow=on
bspc rule -a Register.py state=floating follow=on
bspc rule -a Admin.py state=floating follow=on

#bspc rule -a com-sun-tools-javac-launcher-Main state=floating follow=on

bsp-layout set tall 8

xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape
#$HOME/.config/polybar/launch.sh &
