#! /bin/sh

killall sxhkd
sxhkd &

killall dunst
dunst &
picom &

feh --no-fehbg --bg-fill /home/red/dox/wall/loki_nord.png &

~/dox/dotfiles/polybar/.config/polybar/launch.sh

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI2 -d 9

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#000000"
bspc config border_width 1
bspc config window_gap 10
bspc config top_padding 44
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc rule -a Lxappearance desktop='^2' follow=on
bspc rule -a "Tor Browser" desktop='^5'
bspc rule -a Brave-browser desktop='^2'

#bspc rule -a com-sun-tools-javac-launcher-Main state=floating follow=on

bsp-layout set tall 8
bsp-layout set tall 1

xsetroot -cursor_name left_ptr
setxkbmap -option caps:swapescape
setxkbmap -option escape:caps
#$HOME/.config/polybar/launch.sh &
