#! /bin/sh


xrdb -load /home/red/.config/X11/Xresources
killall sxhkd
sxhkd &

nitrogen --restore

dunst &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focused_border_color   "#656E80"
bspc config normal_border_color  "#232731"
bspc config border_width 2 
bspc config window_gap  10
bspc config top_padding 25
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a "Tor Browser" desktop='^5'
bspc rule -a Brave desktop='^3'
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a com-sun-tools-javac-launcher-Main state=floating follow=on
bspc rule -a mpv focus=off state=floating

setxkbmap -option caps:escape
$HOME/.config/polybar/launch.sh &
